slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan_filter
    mode: mapping
    
    resolution: 0.05
    max_laser_range: 10.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    
    map_update_interval: 0.5  # Publish every 0.5s = 2 Hz