slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan_filter
    mode: mapping
    
    
    resolution: 0.05
    max_laser_range: 20.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
