slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan_filter
    mode: mapping
    
    resolution: 0.05
    max_laser_range: 10.0
    minimum_travel_distance: 0.15
    minimum_travel_heading: 0.15
    
    map_update_interval: 0.5  # Publish every 0.5s = 2 Hz

    # Scan processing
    throttle_scans: 2  # Process every 2nd scan (skip 50%)