teleop_twist_joy_node:
  ros__parameters:
    enable_button: 7  # RB when on rover
    require_enable_button: true
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 2.0
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 2.0